#!/usr/bin/env bash

set -euo pipefail

readonly web_apps=(
  "Basecamp"
  "Google Messages"
  "Google Photos"
  "HEY"
  "Zoom"
)

for web_app in "${web_apps[@]}"; do
  OMARCHY_REMOVE_NOTIFY=false omarchy webapp remove "${web_app}"
done
